namespace WStoreNETAPI
{
    partial class Default
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges33 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges34 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges35 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges36 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Default));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.apikeyLabel = new System.Windows.Forms.Label();
            this.recProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.recentPayments = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.recentTop = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.testQueue = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.testTopCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.keyBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.setButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // guna2BorderlessForm1
            // 
            this.guna2BorderlessForm1.AnimateWindow = true;
            this.guna2BorderlessForm1.AnimationType = Guna.UI2.WinForms.Guna2BorderlessForm.AnimateWindowType.AW_HOR_NEGATIVE;
            this.guna2BorderlessForm1.ContainerControl = this;
            // 
            // guna2ControlBox1
            // 
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(152)))), ((int)(((byte)(166)))));
            this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.White;
            this.guna2ControlBox1.Location = new System.Drawing.Point(436, 2);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.Size = new System.Drawing.Size(45, 29);
            this.guna2ControlBox1.TabIndex = 1;
            this.guna2ControlBox1.Click += new System.EventHandler(this.guna2ControlBox1_Click);
            // 
            // apikeyLabel
            // 
            this.apikeyLabel.AutoSize = true;
            this.apikeyLabel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(54)))), ((int)(((byte)(56)))));
            this.apikeyLabel.ForeColor = System.Drawing.Color.Olive;
            this.apikeyLabel.Location = new System.Drawing.Point(5, 18);
            this.apikeyLabel.Name = "apikeyLabel";
            this.apikeyLabel.Size = new System.Drawing.Size(54, 13);
            this.apikeyLabel.TabIndex = 3;
            this.apikeyLabel.Text = "API KEY: ";
            // 
            // recProduct
            // 
            this.recProduct.AllowAnimations = true;
            this.recProduct.AllowMouseEffects = true;
            this.recProduct.AllowToggling = false;
            this.recProduct.AnimationSpeed = 200;
            this.recProduct.AutoGenerateColors = false;
            this.recProduct.AutoRoundBorders = false;
            this.recProduct.AutoSizeLeftIcon = true;
            this.recProduct.AutoSizeRightIcon = true;
            this.recProduct.BackColor = System.Drawing.Color.Transparent;
            this.recProduct.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.recProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("recProduct.BackgroundImage")));
            this.recProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recProduct.ButtonText = "RECOMMENDED PRODUCT";
            this.recProduct.ButtonTextMarginLeft = 0;
            this.recProduct.ColorContrastOnClick = 45;
            this.recProduct.ColorContrastOnHover = 45;
            this.recProduct.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges30.BottomLeft = true;
            borderEdges30.BottomRight = true;
            borderEdges30.TopLeft = true;
            borderEdges30.TopRight = true;
            this.recProduct.CustomizableEdges = borderEdges30;
            this.recProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.recProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recProduct.DisabledFillColor = System.Drawing.Color.Empty;
            this.recProduct.DisabledForecolor = System.Drawing.Color.Empty;
            this.recProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.recProduct.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.recProduct.ForeColor = System.Drawing.Color.Coral;
            this.recProduct.IconLeft = null;
            this.recProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.recProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.recProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.recProduct.IconMarginLeft = 11;
            this.recProduct.IconPadding = 10;
            this.recProduct.IconRight = null;
            this.recProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.recProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.recProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.recProduct.IconSize = 25;
            this.recProduct.IdleBorderColor = System.Drawing.Color.Empty;
            this.recProduct.IdleBorderRadius = 0;
            this.recProduct.IdleBorderThickness = 0;
            this.recProduct.IdleFillColor = System.Drawing.Color.Empty;
            this.recProduct.IdleIconLeftImage = null;
            this.recProduct.IdleIconRightImage = null;
            this.recProduct.IndicateFocus = false;
            this.recProduct.Location = new System.Drawing.Point(319, 168);
            this.recProduct.Name = "recProduct";
            this.recProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recProduct.OnDisabledState.BorderRadius = 1;
            this.recProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recProduct.OnDisabledState.BorderThickness = 1;
            this.recProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.recProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.recProduct.OnDisabledState.IconLeftImage = null;
            this.recProduct.OnDisabledState.IconRightImage = null;
            this.recProduct.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recProduct.onHoverState.BorderRadius = 1;
            this.recProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recProduct.onHoverState.BorderThickness = 1;
            this.recProduct.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.recProduct.onHoverState.IconLeftImage = null;
            this.recProduct.onHoverState.IconRightImage = null;
            this.recProduct.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.recProduct.OnIdleState.BorderRadius = 1;
            this.recProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recProduct.OnIdleState.BorderThickness = 1;
            this.recProduct.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.recProduct.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.recProduct.OnIdleState.IconLeftImage = null;
            this.recProduct.OnIdleState.IconRightImage = null;
            this.recProduct.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recProduct.OnPressedState.BorderRadius = 1;
            this.recProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recProduct.OnPressedState.BorderThickness = 1;
            this.recProduct.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.recProduct.OnPressedState.IconLeftImage = null;
            this.recProduct.OnPressedState.IconRightImage = null;
            this.recProduct.Size = new System.Drawing.Size(150, 39);
            this.recProduct.TabIndex = 10;
            this.recProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.recProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.recProduct.TextMarginLeft = 0;
            this.recProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.recProduct.UseDefaultRadiusAndThickness = true;
            this.recProduct.Click += new System.EventHandler(this.recProduct_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "GOAL";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges31.BottomLeft = true;
            borderEdges31.BottomRight = true;
            borderEdges31.TopLeft = true;
            borderEdges31.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges31;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(161, 168);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 9;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // recentPayments
            // 
            this.recentPayments.AllowAnimations = true;
            this.recentPayments.AllowMouseEffects = true;
            this.recentPayments.AllowToggling = false;
            this.recentPayments.AnimationSpeed = 200;
            this.recentPayments.AutoGenerateColors = false;
            this.recentPayments.AutoRoundBorders = false;
            this.recentPayments.AutoSizeLeftIcon = true;
            this.recentPayments.AutoSizeRightIcon = true;
            this.recentPayments.BackColor = System.Drawing.Color.Transparent;
            this.recentPayments.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.recentPayments.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("recentPayments.BackgroundImage")));
            this.recentPayments.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentPayments.ButtonText = "RECENT PAYMENTS";
            this.recentPayments.ButtonTextMarginLeft = 0;
            this.recentPayments.ColorContrastOnClick = 45;
            this.recentPayments.ColorContrastOnHover = 45;
            this.recentPayments.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges32.BottomLeft = true;
            borderEdges32.BottomRight = true;
            borderEdges32.TopLeft = true;
            borderEdges32.TopRight = true;
            this.recentPayments.CustomizableEdges = borderEdges32;
            this.recentPayments.DialogResult = System.Windows.Forms.DialogResult.None;
            this.recentPayments.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recentPayments.DisabledFillColor = System.Drawing.Color.Empty;
            this.recentPayments.DisabledForecolor = System.Drawing.Color.Empty;
            this.recentPayments.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.recentPayments.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.recentPayments.ForeColor = System.Drawing.Color.Coral;
            this.recentPayments.IconLeft = null;
            this.recentPayments.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.recentPayments.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.recentPayments.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.recentPayments.IconMarginLeft = 11;
            this.recentPayments.IconPadding = 10;
            this.recentPayments.IconRight = null;
            this.recentPayments.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.recentPayments.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.recentPayments.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.recentPayments.IconSize = 25;
            this.recentPayments.IdleBorderColor = System.Drawing.Color.Empty;
            this.recentPayments.IdleBorderRadius = 0;
            this.recentPayments.IdleBorderThickness = 0;
            this.recentPayments.IdleFillColor = System.Drawing.Color.Empty;
            this.recentPayments.IdleIconLeftImage = null;
            this.recentPayments.IdleIconRightImage = null;
            this.recentPayments.IndicateFocus = false;
            this.recentPayments.Location = new System.Drawing.Point(5, 168);
            this.recentPayments.Name = "recentPayments";
            this.recentPayments.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recentPayments.OnDisabledState.BorderRadius = 1;
            this.recentPayments.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentPayments.OnDisabledState.BorderThickness = 1;
            this.recentPayments.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.recentPayments.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.recentPayments.OnDisabledState.IconLeftImage = null;
            this.recentPayments.OnDisabledState.IconRightImage = null;
            this.recentPayments.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recentPayments.onHoverState.BorderRadius = 1;
            this.recentPayments.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentPayments.onHoverState.BorderThickness = 1;
            this.recentPayments.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recentPayments.onHoverState.ForeColor = System.Drawing.Color.White;
            this.recentPayments.onHoverState.IconLeftImage = null;
            this.recentPayments.onHoverState.IconRightImage = null;
            this.recentPayments.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.recentPayments.OnIdleState.BorderRadius = 1;
            this.recentPayments.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentPayments.OnIdleState.BorderThickness = 1;
            this.recentPayments.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.recentPayments.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.recentPayments.OnIdleState.IconLeftImage = null;
            this.recentPayments.OnIdleState.IconRightImage = null;
            this.recentPayments.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recentPayments.OnPressedState.BorderRadius = 1;
            this.recentPayments.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentPayments.OnPressedState.BorderThickness = 1;
            this.recentPayments.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recentPayments.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.recentPayments.OnPressedState.IconLeftImage = null;
            this.recentPayments.OnPressedState.IconRightImage = null;
            this.recentPayments.Size = new System.Drawing.Size(150, 39);
            this.recentPayments.TabIndex = 8;
            this.recentPayments.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.recentPayments.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.recentPayments.TextMarginLeft = 0;
            this.recentPayments.TextPadding = new System.Windows.Forms.Padding(0);
            this.recentPayments.UseDefaultRadiusAndThickness = true;
            this.recentPayments.Click += new System.EventHandler(this.recentPayments_Click);
            // 
            // recentTop
            // 
            this.recentTop.AllowAnimations = true;
            this.recentTop.AllowMouseEffects = true;
            this.recentTop.AllowToggling = false;
            this.recentTop.AnimationSpeed = 200;
            this.recentTop.AutoGenerateColors = false;
            this.recentTop.AutoRoundBorders = false;
            this.recentTop.AutoSizeLeftIcon = true;
            this.recentTop.AutoSizeRightIcon = true;
            this.recentTop.BackColor = System.Drawing.Color.Transparent;
            this.recentTop.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.recentTop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("recentTop.BackgroundImage")));
            this.recentTop.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentTop.ButtonText = "RECENT TOP CUSTOMERS";
            this.recentTop.ButtonTextMarginLeft = 0;
            this.recentTop.ColorContrastOnClick = 45;
            this.recentTop.ColorContrastOnHover = 45;
            this.recentTop.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges33.BottomLeft = true;
            borderEdges33.BottomRight = true;
            borderEdges33.TopLeft = true;
            borderEdges33.TopRight = true;
            this.recentTop.CustomizableEdges = borderEdges33;
            this.recentTop.DialogResult = System.Windows.Forms.DialogResult.None;
            this.recentTop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recentTop.DisabledFillColor = System.Drawing.Color.Empty;
            this.recentTop.DisabledForecolor = System.Drawing.Color.Empty;
            this.recentTop.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.recentTop.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.recentTop.ForeColor = System.Drawing.Color.Coral;
            this.recentTop.IconLeft = null;
            this.recentTop.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.recentTop.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.recentTop.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.recentTop.IconMarginLeft = 11;
            this.recentTop.IconPadding = 10;
            this.recentTop.IconRight = null;
            this.recentTop.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.recentTop.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.recentTop.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.recentTop.IconSize = 25;
            this.recentTop.IdleBorderColor = System.Drawing.Color.Empty;
            this.recentTop.IdleBorderRadius = 0;
            this.recentTop.IdleBorderThickness = 0;
            this.recentTop.IdleFillColor = System.Drawing.Color.Empty;
            this.recentTop.IdleIconLeftImage = null;
            this.recentTop.IdleIconRightImage = null;
            this.recentTop.IndicateFocus = false;
            this.recentTop.Location = new System.Drawing.Point(317, 110);
            this.recentTop.Name = "recentTop";
            this.recentTop.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recentTop.OnDisabledState.BorderRadius = 1;
            this.recentTop.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentTop.OnDisabledState.BorderThickness = 1;
            this.recentTop.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.recentTop.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.recentTop.OnDisabledState.IconLeftImage = null;
            this.recentTop.OnDisabledState.IconRightImage = null;
            this.recentTop.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recentTop.onHoverState.BorderRadius = 1;
            this.recentTop.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentTop.onHoverState.BorderThickness = 1;
            this.recentTop.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.recentTop.onHoverState.ForeColor = System.Drawing.Color.White;
            this.recentTop.onHoverState.IconLeftImage = null;
            this.recentTop.onHoverState.IconRightImage = null;
            this.recentTop.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.recentTop.OnIdleState.BorderRadius = 1;
            this.recentTop.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentTop.OnIdleState.BorderThickness = 1;
            this.recentTop.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.recentTop.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.recentTop.OnIdleState.IconLeftImage = null;
            this.recentTop.OnIdleState.IconRightImage = null;
            this.recentTop.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recentTop.OnPressedState.BorderRadius = 1;
            this.recentTop.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recentTop.OnPressedState.BorderThickness = 1;
            this.recentTop.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.recentTop.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.recentTop.OnPressedState.IconLeftImage = null;
            this.recentTop.OnPressedState.IconRightImage = null;
            this.recentTop.Size = new System.Drawing.Size(150, 39);
            this.recentTop.TabIndex = 7;
            this.recentTop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.recentTop.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.recentTop.TextMarginLeft = 0;
            this.recentTop.TextPadding = new System.Windows.Forms.Padding(0);
            this.recentTop.UseDefaultRadiusAndThickness = true;
            this.recentTop.Click += new System.EventHandler(this.recentTop_Click);
            // 
            // testQueue
            // 
            this.testQueue.AllowAnimations = true;
            this.testQueue.AllowMouseEffects = true;
            this.testQueue.AllowToggling = false;
            this.testQueue.AnimationSpeed = 200;
            this.testQueue.AutoGenerateColors = false;
            this.testQueue.AutoRoundBorders = false;
            this.testQueue.AutoSizeLeftIcon = true;
            this.testQueue.AutoSizeRightIcon = true;
            this.testQueue.BackColor = System.Drawing.Color.Transparent;
            this.testQueue.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.testQueue.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("testQueue.BackgroundImage")));
            this.testQueue.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testQueue.ButtonText = "TEST QUEUE";
            this.testQueue.ButtonTextMarginLeft = 0;
            this.testQueue.ColorContrastOnClick = 45;
            this.testQueue.ColorContrastOnHover = 45;
            this.testQueue.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges34.BottomLeft = true;
            borderEdges34.BottomRight = true;
            borderEdges34.TopLeft = true;
            borderEdges34.TopRight = true;
            this.testQueue.CustomizableEdges = borderEdges34;
            this.testQueue.DialogResult = System.Windows.Forms.DialogResult.None;
            this.testQueue.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.testQueue.DisabledFillColor = System.Drawing.Color.Empty;
            this.testQueue.DisabledForecolor = System.Drawing.Color.Empty;
            this.testQueue.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.testQueue.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.testQueue.ForeColor = System.Drawing.Color.Coral;
            this.testQueue.IconLeft = null;
            this.testQueue.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.testQueue.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.testQueue.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.testQueue.IconMarginLeft = 11;
            this.testQueue.IconPadding = 10;
            this.testQueue.IconRight = null;
            this.testQueue.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.testQueue.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.testQueue.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.testQueue.IconSize = 25;
            this.testQueue.IdleBorderColor = System.Drawing.Color.Empty;
            this.testQueue.IdleBorderRadius = 0;
            this.testQueue.IdleBorderThickness = 0;
            this.testQueue.IdleFillColor = System.Drawing.Color.Empty;
            this.testQueue.IdleIconLeftImage = null;
            this.testQueue.IdleIconRightImage = null;
            this.testQueue.IndicateFocus = false;
            this.testQueue.Location = new System.Drawing.Point(161, 110);
            this.testQueue.Name = "testQueue";
            this.testQueue.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.testQueue.OnDisabledState.BorderRadius = 1;
            this.testQueue.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testQueue.OnDisabledState.BorderThickness = 1;
            this.testQueue.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.testQueue.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.testQueue.OnDisabledState.IconLeftImage = null;
            this.testQueue.OnDisabledState.IconRightImage = null;
            this.testQueue.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.testQueue.onHoverState.BorderRadius = 1;
            this.testQueue.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testQueue.onHoverState.BorderThickness = 1;
            this.testQueue.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.testQueue.onHoverState.ForeColor = System.Drawing.Color.White;
            this.testQueue.onHoverState.IconLeftImage = null;
            this.testQueue.onHoverState.IconRightImage = null;
            this.testQueue.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.testQueue.OnIdleState.BorderRadius = 1;
            this.testQueue.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testQueue.OnIdleState.BorderThickness = 1;
            this.testQueue.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.testQueue.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.testQueue.OnIdleState.IconLeftImage = null;
            this.testQueue.OnIdleState.IconRightImage = null;
            this.testQueue.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.testQueue.OnPressedState.BorderRadius = 1;
            this.testQueue.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testQueue.OnPressedState.BorderThickness = 1;
            this.testQueue.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.testQueue.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.testQueue.OnPressedState.IconLeftImage = null;
            this.testQueue.OnPressedState.IconRightImage = null;
            this.testQueue.Size = new System.Drawing.Size(150, 39);
            this.testQueue.TabIndex = 6;
            this.testQueue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.testQueue.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.testQueue.TextMarginLeft = 0;
            this.testQueue.TextPadding = new System.Windows.Forms.Padding(0);
            this.testQueue.UseDefaultRadiusAndThickness = true;
            this.testQueue.Click += new System.EventHandler(this.testQueue_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::WStoreNETAPI.Properties.Resources.w_store_white_logo;
            this.pictureBox1.Location = new System.Drawing.Point(157, 280);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(176, 64);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // testTopCustomer
            // 
            this.testTopCustomer.AllowAnimations = true;
            this.testTopCustomer.AllowMouseEffects = true;
            this.testTopCustomer.AllowToggling = false;
            this.testTopCustomer.AnimationSpeed = 200;
            this.testTopCustomer.AutoGenerateColors = false;
            this.testTopCustomer.AutoRoundBorders = false;
            this.testTopCustomer.AutoSizeLeftIcon = true;
            this.testTopCustomer.AutoSizeRightIcon = true;
            this.testTopCustomer.BackColor = System.Drawing.Color.Transparent;
            this.testTopCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.testTopCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("testTopCustomer.BackgroundImage")));
            this.testTopCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testTopCustomer.ButtonText = "TEST TOP CUSTOMER";
            this.testTopCustomer.ButtonTextMarginLeft = 0;
            this.testTopCustomer.ColorContrastOnClick = 45;
            this.testTopCustomer.ColorContrastOnHover = 45;
            this.testTopCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges35.BottomLeft = true;
            borderEdges35.BottomRight = true;
            borderEdges35.TopLeft = true;
            borderEdges35.TopRight = true;
            this.testTopCustomer.CustomizableEdges = borderEdges35;
            this.testTopCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.testTopCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.testTopCustomer.DisabledFillColor = System.Drawing.Color.Empty;
            this.testTopCustomer.DisabledForecolor = System.Drawing.Color.Empty;
            this.testTopCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.testTopCustomer.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.testTopCustomer.ForeColor = System.Drawing.Color.Coral;
            this.testTopCustomer.IconLeft = null;
            this.testTopCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.testTopCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.testTopCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.testTopCustomer.IconMarginLeft = 11;
            this.testTopCustomer.IconPadding = 10;
            this.testTopCustomer.IconRight = null;
            this.testTopCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.testTopCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.testTopCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.testTopCustomer.IconSize = 25;
            this.testTopCustomer.IdleBorderColor = System.Drawing.Color.Empty;
            this.testTopCustomer.IdleBorderRadius = 0;
            this.testTopCustomer.IdleBorderThickness = 0;
            this.testTopCustomer.IdleFillColor = System.Drawing.Color.Empty;
            this.testTopCustomer.IdleIconLeftImage = null;
            this.testTopCustomer.IdleIconRightImage = null;
            this.testTopCustomer.IndicateFocus = false;
            this.testTopCustomer.Location = new System.Drawing.Point(5, 110);
            this.testTopCustomer.Name = "testTopCustomer";
            this.testTopCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.testTopCustomer.OnDisabledState.BorderRadius = 1;
            this.testTopCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testTopCustomer.OnDisabledState.BorderThickness = 1;
            this.testTopCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.testTopCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.testTopCustomer.OnDisabledState.IconLeftImage = null;
            this.testTopCustomer.OnDisabledState.IconRightImage = null;
            this.testTopCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.testTopCustomer.onHoverState.BorderRadius = 1;
            this.testTopCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testTopCustomer.onHoverState.BorderThickness = 1;
            this.testTopCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.testTopCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.testTopCustomer.onHoverState.IconLeftImage = null;
            this.testTopCustomer.onHoverState.IconRightImage = null;
            this.testTopCustomer.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.testTopCustomer.OnIdleState.BorderRadius = 1;
            this.testTopCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testTopCustomer.OnIdleState.BorderThickness = 1;
            this.testTopCustomer.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.testTopCustomer.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.testTopCustomer.OnIdleState.IconLeftImage = null;
            this.testTopCustomer.OnIdleState.IconRightImage = null;
            this.testTopCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.testTopCustomer.OnPressedState.BorderRadius = 1;
            this.testTopCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.testTopCustomer.OnPressedState.BorderThickness = 1;
            this.testTopCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.testTopCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.testTopCustomer.OnPressedState.IconLeftImage = null;
            this.testTopCustomer.OnPressedState.IconRightImage = null;
            this.testTopCustomer.Size = new System.Drawing.Size(150, 39);
            this.testTopCustomer.TabIndex = 5;
            this.testTopCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.testTopCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.testTopCustomer.TextMarginLeft = 0;
            this.testTopCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.testTopCustomer.UseDefaultRadiusAndThickness = true;
            this.testTopCustomer.Click += new System.EventHandler(this.testTopCustomer_Click);
            // 
            // keyBox
            // 
            this.keyBox.AcceptsReturn = false;
            this.keyBox.AcceptsTab = false;
            this.keyBox.AnimationSpeed = 200;
            this.keyBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.keyBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.keyBox.AutoSizeHeight = true;
            this.keyBox.BackColor = System.Drawing.Color.Transparent;
            this.keyBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("keyBox.BackgroundImage")));
            this.keyBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.keyBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.keyBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.keyBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.keyBox.BorderRadius = 10;
            this.keyBox.BorderThickness = 5;
            this.keyBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.keyBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.keyBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.keyBox.DefaultText = "";
            this.keyBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(54)))), ((int)(((byte)(56)))));
            this.keyBox.HideSelection = true;
            this.keyBox.IconLeft = null;
            this.keyBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.keyBox.IconPadding = 10;
            this.keyBox.IconRight = null;
            this.keyBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.keyBox.Lines = new string[0];
            this.keyBox.Location = new System.Drawing.Point(56, 12);
            this.keyBox.MaxLength = 32767;
            this.keyBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.keyBox.Modified = false;
            this.keyBox.Multiline = false;
            this.keyBox.Name = "keyBox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.keyBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.keyBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.keyBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(54)))), ((int)(((byte)(56)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.keyBox.OnIdleState = stateProperties16;
            this.keyBox.Padding = new System.Windows.Forms.Padding(3);
            this.keyBox.PasswordChar = '\0';
            this.keyBox.PlaceholderForeColor = System.Drawing.Color.Yellow;
            this.keyBox.PlaceholderText = "Enter API Key";
            this.keyBox.ReadOnly = false;
            this.keyBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.keyBox.SelectedText = "";
            this.keyBox.SelectionLength = 0;
            this.keyBox.SelectionStart = 0;
            this.keyBox.ShortcutsEnabled = true;
            this.keyBox.Size = new System.Drawing.Size(260, 29);
            this.keyBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.keyBox.TabIndex = 4;
            this.keyBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.keyBox.TextMarginBottom = 0;
            this.keyBox.TextMarginLeft = 3;
            this.keyBox.TextMarginTop = 1;
            this.keyBox.TextPlaceholder = "Enter API Key";
            this.keyBox.UseSystemPasswordChar = false;
            this.keyBox.WordWrap = true;
            // 
            // setButton
            // 
            this.setButton.AllowAnimations = true;
            this.setButton.AllowMouseEffects = true;
            this.setButton.AllowToggling = false;
            this.setButton.AnimationSpeed = 200;
            this.setButton.AutoGenerateColors = false;
            this.setButton.AutoRoundBorders = false;
            this.setButton.AutoSizeLeftIcon = true;
            this.setButton.AutoSizeRightIcon = true;
            this.setButton.BackColor = System.Drawing.Color.Transparent;
            this.setButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.setButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("setButton.BackgroundImage")));
            this.setButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.setButton.ButtonText = "SET";
            this.setButton.ButtonTextMarginLeft = 0;
            this.setButton.ColorContrastOnClick = 45;
            this.setButton.ColorContrastOnHover = 45;
            this.setButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges36.BottomLeft = true;
            borderEdges36.BottomRight = true;
            borderEdges36.TopLeft = true;
            borderEdges36.TopRight = true;
            this.setButton.CustomizableEdges = borderEdges36;
            this.setButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.setButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.setButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.setButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.setButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.setButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.setButton.ForeColor = System.Drawing.Color.White;
            this.setButton.IconLeft = null;
            this.setButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.setButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.setButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.setButton.IconMarginLeft = 11;
            this.setButton.IconPadding = 10;
            this.setButton.IconRight = null;
            this.setButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.setButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.setButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.setButton.IconSize = 25;
            this.setButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.setButton.IdleBorderRadius = 0;
            this.setButton.IdleBorderThickness = 0;
            this.setButton.IdleFillColor = System.Drawing.Color.Empty;
            this.setButton.IdleIconLeftImage = null;
            this.setButton.IdleIconRightImage = null;
            this.setButton.IndicateFocus = false;
            this.setButton.Location = new System.Drawing.Point(322, 18);
            this.setButton.Name = "setButton";
            this.setButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.setButton.OnDisabledState.BorderRadius = 1;
            this.setButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.setButton.OnDisabledState.BorderThickness = 1;
            this.setButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.setButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.setButton.OnDisabledState.IconLeftImage = null;
            this.setButton.OnDisabledState.IconRightImage = null;
            this.setButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.setButton.onHoverState.BorderRadius = 1;
            this.setButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.setButton.onHoverState.BorderThickness = 1;
            this.setButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.setButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.setButton.onHoverState.IconLeftImage = null;
            this.setButton.onHoverState.IconRightImage = null;
            this.setButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.setButton.OnIdleState.BorderRadius = 1;
            this.setButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.setButton.OnIdleState.BorderThickness = 1;
            this.setButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.setButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.setButton.OnIdleState.IconLeftImage = null;
            this.setButton.OnIdleState.IconRightImage = null;
            this.setButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.setButton.OnPressedState.BorderRadius = 1;
            this.setButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.setButton.OnPressedState.BorderThickness = 1;
            this.setButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.setButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.setButton.OnPressedState.IconLeftImage = null;
            this.setButton.OnPressedState.IconRightImage = null;
            this.setButton.Size = new System.Drawing.Size(89, 28);
            this.setButton.TabIndex = 2;
            this.setButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.setButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.setButton.TextMarginLeft = 0;
            this.setButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.setButton.UseDefaultRadiusAndThickness = true;
            this.setButton.Click += new System.EventHandler(this.setButton_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "GET INFO FROM PRODUCT ID";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges29.BottomLeft = true;
            borderEdges29.BottomRight = true;
            borderEdges29.TopLeft = true;
            borderEdges29.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges29;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(5, 223);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(194, 39);
            this.bunifuButton2.TabIndex = 11;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "GET INFO FROM PRODUCT CATEGORY\r\n";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges28.BottomLeft = true;
            borderEdges28.BottomRight = true;
            borderEdges28.TopLeft = true;
            borderEdges28.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges28;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton3.IconLeft = null;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRight = null;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleBorderRadius = 0;
            this.bunifuButton3.IdleBorderThickness = 0;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(217, 223);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.SkyBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.Plum;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.Coral;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(250, 39);
            this.bunifuButton3.TabIndex = 12;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(54)))), ((int)(((byte)(56)))));
            this.label1.ForeColor = System.Drawing.Color.Olive;
            this.label1.Location = new System.Drawing.Point(93, 76);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(294, 13);
            this.label1.TabIndex = 13;
            this.label1.Text = "Source Code : https://github.com/dayofpay/WStoreNETAPI";
            // 
            // Default
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(54)))), ((int)(((byte)(56)))));
            this.ClientSize = new System.Drawing.Size(481, 346);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.bunifuButton2);
            this.Controls.Add(this.recProduct);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.recentPayments);
            this.Controls.Add(this.recentTop);
            this.Controls.Add(this.testQueue);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.testTopCustomer);
            this.Controls.Add(this.keyBox);
            this.Controls.Add(this.apikeyLabel);
            this.Controls.Add(this.setButton);
            this.Controls.Add(this.guna2ControlBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Default";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Default_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton setButton;
        private System.Windows.Forms.Label apikeyLabel;
        private Bunifu.UI.WinForms.BunifuTextBox keyBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton testTopCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton testQueue;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton recentTop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton recentPayments;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton recProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private System.Windows.Forms.Label label1;
    }
}

